[build]
  command = "./netlify-build.sh"
  publish = "netlify-dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  BUN_INSTALL = "true"
  # Set working directory for build
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false"

# Handle Next.js routing with internationalization
# Priority order for redirects matters!

# 1. API routes first
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# 2. Handle specific Next.js routes
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# 3. Handle locale-based routes (en, zh, ko, ja)
[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/zh/*"
  to = "/zh/index.html"
  status = 200

[[redirects]]
  from = "/ko/*"
  to = "/ko/index.html"
  status = 200

[[redirects]]
  from = "/ja/*"
  to = "/ja/index.html"
  status = 200

# 4. Handle root locale redirects (default to zh)
[[redirects]]
  from = "/"
  to = "/zh/"
  status = 301

# 5. Fallback for any other routes - serve static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Functions configuration
[functions]
  node_bundler = "esbuild"

[dev]
  command = "cd saasfly && bun run dev"
  port = 3000
  publish = "saasfly/apps/nextjs/.next"